from __future__ import annotations

import argparse
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
UPDATES_DIR = ROOT / "docs" / "updates"
INDEX_PATH = UPDATES_DIR / "INDEX.md"


def _slugify(value: str) -> str:
    cleaned = re.sub(r"[^a-z0-9]+", "-", value.strip().lower())
    cleaned = cleaned.strip("-")
    return cleaned[:72] or "project-update"


def _timestamp_parts() -> tuple[str, str]:
    now_utc = datetime.now(timezone.utc)
    file_stamp = now_utc.strftime("%Y-%m-%d_%H%M%S")
    label = now_utc.strftime("%Y-%m-%d %H:%M:%S UTC")
    return file_stamp, label


def _detect_changed_files() -> list[str]:
    git_dir = ROOT / ".git"
    if not git_dir.exists():
        return []
    try:
        result = subprocess.run(
            ["git", "-C", str(ROOT), "status", "--short"],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return []
    if result.returncode != 0:
        return []
    files: list[str] = []
    for line in result.stdout.splitlines():
        trimmed = line.strip()
        if not trimmed:
            continue
        path = trimmed[3:].strip()
        if path:
            files.append(path)
    return files


def _ensure_index() -> None:
    if INDEX_PATH.exists():
        return
    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(
        "# Project Update Index\n\n"
        "This index tracks timestamped update summary files generated by `scripts/log_update.py`.\n\n"
        "## Entries\n\n",
        encoding="utf-8",
    )


def _append_to_index(file_name: str, timestamp_label: str, title: str) -> None:
    _ensure_index()
    entry = f"- {timestamp_label} - [{title}](./{file_name})\n"
    with INDEX_PATH.open("a", encoding="utf-8") as handle:
        handle.write(entry)


def _build_content(
    *,
    title: str,
    summary: str,
    timestamp_label: str,
    details: list[str],
    changed_files: list[str],
) -> str:
    detail_lines = "\n".join(f"- {item}" for item in details) if details else "- No extra details were provided."
    file_lines = "\n".join(f"- `{path}`" for path in changed_files) if changed_files else "- No file list was provided."
    return (
        f"# Update Summary: {title}\n\n"
        f"- Timestamp: {timestamp_label}\n"
        f"- Summary: {summary}\n\n"
        "## Details\n\n"
        f"{detail_lines}\n\n"
        "## Changed Files\n\n"
        f"{file_lines}\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a timestamped project update summary in docs/updates and append it to the index."
    )
    parser.add_argument("--title", required=True, help="Short title for this update.")
    parser.add_argument(
        "--summary",
        required=True,
        help="One-line summary of what changed.",
    )
    parser.add_argument(
        "--detail",
        action="append",
        default=[],
        help="Optional detail line. Repeat for multiple details.",
    )
    parser.add_argument(
        "--changed-file",
        action="append",
        default=[],
        help="Optional changed file path. Repeat for multiple files.",
    )
    parser.add_argument(
        "--no-auto-files",
        action="store_true",
        help="Disable auto-detecting changed files from git status.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    file_stamp, timestamp_label = _timestamp_parts()
    slug = _slugify(args.title)
    file_name = f"{file_stamp}_{slug}.md"
    file_path = UPDATES_DIR / file_name

    UPDATES_DIR.mkdir(parents=True, exist_ok=True)
    auto_files = [] if args.no_auto_files else _detect_changed_files()
    changed_files = list(dict.fromkeys([*args.changed_file, *auto_files]))

    content = _build_content(
        title=args.title,
        summary=args.summary,
        timestamp_label=timestamp_label,
        details=args.detail,
        changed_files=changed_files,
    )
    file_path.write_text(content, encoding="utf-8")
    _append_to_index(file_name=file_name, timestamp_label=timestamp_label, title=args.title)
    print(f"Created update summary: {file_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
